### ISSUE TITLE
Set up Netlify Deployment Preview

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5-ng#12]
**Desired Behavior**
As suggested in the community meeting we should set up Netlify deployment preview as in the `Layer5` repo. This will help in easier review of PRs.

**Comment by Tanuj22** [comment]
@leecalcote @shivaylamba I am not sure if I can do this. There is an option for me to request access from netlify to this repo. Should I do that or was it done in a different way in the `Layer5` repo?

**Comment by leecalcote** [comment]
@Tanuj22 yes, let's get you access to the team account.

**Comment by leecalcote** [comment]
Fixed by #14

**Comment by leecalcote** [comment]
Good work, @Tanuj22
